import type { Product } from "@/features/products/types/product.types";

export const mockProducts: Product[] = [
  {
    id: "fleur-de-lune",
    name: "Fleur de Lune",
    description: "A luminous floral composition of jasmine and white musk.",
    notes: "Floral / Jasmine & White Musk",
    price: 195,
    images: ["/images/products/fleur-de-lune.png"],
    category: "pure-extractions",
    scentFamily: "floral",
    occasion: "personal-use",
    options: [],
    volumeOptions: [
      { id: "30-ml", label: "30 ml", price: 125 },
      { id: "50-ml", label: "50 ml", price: 165 },
      { id: "100-ml", label: "100 ml", price: 195 },
    ],
    scentAnatomy:
      "A luminous floral composition of jasmine and white musk, softened with a sheer, moonlit finish.",
    scentNotes: {
      top: "Bergamot, pear blossom",
      heart: "Jasmine sambac, iris",
      base: "White musk, soft woods",
    },
    availability: "Available in Atelier",
  },
  {
    id: "santal-parchment",
    name: "Santal Parchment",
    description: "Warm sandalwood layered with cardamom.",
    notes: "Woody / Sandalwood & Cardamom",
    price: 220,
    images: ["/images/products/santal-parchment.png"],
    category: "pure-extractions",
    scentFamily: "woody",
    occasion: "personal-use",
    options: [],
    volumeOptions: [
      { id: "30-ml", label: "30 ml", price: 140 },
      { id: "50-ml", label: "50 ml", price: 180 },
      { id: "100-ml", label: "100 ml", price: 220 },
    ],
    scentAnatomy:
      "Santal Parchment wraps around the skin like vintage vellum paper. It opens with bright top notes, shifting to clean papyrus and warm, rich sandalwood that dry down into dry cardamom and amber.",
    scentNotes: {
      top: "Sicilian Bergamot, Pink Pepper",
      heart: "Egyptian Jasmine Sambac, Papyrus",
      base: "West Indian Sandalwood, Cardamom, Amber",
    },
    availability: "Available in Atelier",
  },
  {
    id: "noir-cocoon",
    name: "Noir Cocoon",
    description: "An oriental blend of tobacco and amber.",
    notes: "Oriental / Tobacco & Amber",
    price: 240,
    images: ["/images/products/noir-cocoon.png"],
    category: "private-reserve",
    scentFamily: "oriental",
    occasion: "wedding",
    options: [],
    volumeOptions: [
      { id: "30-ml", label: "30 ml", price: 155 },
      { id: "50-ml", label: "50 ml", price: 195 },
      { id: "100-ml", label: "100 ml", price: 240 },
    ],
    scentAnatomy:
      "A dark, enveloping blend where tobacco leaf and amber glow beneath a polished, resinous finish.",
    scentNotes: {
      top: "Black pepper, dried citrus",
      heart: "Tobacco leaf, leather",
      base: "Amber, cedar, tonka",
    },
    availability: "Available in Atelier",
  },
  {
    id: "sol-dor",
    name: "Sol d'Or",
    description: "A fresh coastal blend of bergamot and sea salt.",
    notes: "Fresh / Bergamot & Sea Salt",
    price: 185,
    images: ["/images/products/sol-dor.png"],
    category: "pure-extractions",
    scentFamily: "fresh",
    occasion: "personal-use",
    options: [],
    availability: "Available in Atelier",
  },
  {
    id: "atelier-oud",
    name: "Atelier Oud",
    description: "Rich oud deepened with saffron.",
    notes: "Woody / Rich Oud & Saffron",
    price: 310,
    images: ["/images/products/atelier-oud.png"],
    category: "atelier-oils",
    scentFamily: "woody",
    occasion: "gift-sets",
    options: [],
    availability: "Available in Atelier",
  },
  {
    id: "rose-absolute",
    name: "Rose Absolute",
    description: "Damask rose balanced with cedar.",
    notes: "Floral / Damask Rose & Cedar",
    price: 205,
    images: ["/images/products/rose-absolute.png"],
    category: "private-reserve",
    scentFamily: "floral",
    occasion: "birthday",
    options: [],
    availability: "Available in Atelier",
  },
];
